# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the following line.
# disable_cocoapods_analytics!

flutter_root = File.expand_path('..', File.dirname(__FILE__))

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

project 'Runner', {
  'Debug' => :project_default,
  'Profile' => :project_default,
  'Release' => :project_default,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
